;;; apropospriate-claude-dark-theme.el --- Dark theme with real Claude.ai colors.
;;; Code:
(deftheme apropospriate-claude-dark "Dark theme using real Claude.ai colors")
(let* ((class '((class color) (min-colors 89)))
       (base00   "#1f1f1e")
       (base00-1 "#171716")
       (base00-2 "#0f0f0f")
       (base00-3 "#0a0a09")
       (base00+05 "#272725")
       (base00+1 "#2c2c2a")
       (base00+2 "#383836")
       (base00+3 "#444442")
       (base03 "#d3d7de")
       (base02 "#9aa0aa")
       (base01 "#818898")
       (purple   "#cc7bf4")
       (pink     "#f47b85")
       (orange   "#fbad60")
       (cyan     "#5eedee")
       (green    "#9be963")
       (green-1  "#7acc4a")
       (blue     "#3d8fe0")
       (blue-1   "#7ab8ef")
       (red      "#e04040")
       (red-1    "#e88080")
       (yellow-1 "#ffd080")
       (teal     "#5eaaa0")
       (indigo   "#8888cc")
       (brown    "#a48870")
       (highlight-line-color base00+05))
  (custom-theme-set-faces
   'apropospriate-claude-dark
   `(default ((,class (:background ,base00 :foreground ,base03))))
   `(bold ((,class (:weight bold))))
   `(cursor ((,class (:background ,orange :inverse-video t))))
   `(highlight ((,class (:background ,base00+2))))
   `(hl-line ((,class (:background ,highlight-line-color))))
   `(link ((,class (:foreground ,blue :underline t))))
   `(link-visited ((,class (:inherit link :foreground ,purple))))
   `(minibuffer-prompt ((,class (:foreground ,orange :weight bold))))
   `(region ((,class (:background ,base00+3 :foreground ,base03))))
   `(secondary-selection ((,class (:background ,base00-1))))
   `(header-line ((,class (:foreground ,orange :background nil))))
   `(fringe ((,class (:background ,base00 :foreground ,base01))))
   `(vertical-border ((,class (:foreground ,base00+1))))
   `(error ((,class (:foreground ,red :weight bold))))
   `(warning ((,class (:foreground ,orange :weight bold))))
   `(success ((,class (:foreground ,green :weight bold))))
   `(linum ((,class (:background ,base00 :foreground ,base01))))
   `(line-number ((,class (:background ,base00 :foreground ,base01))))
   `(line-number-current-line ((,class (:background ,base00+05 :foreground ,base02))))
   `(mode-line ((,class (:box (:line-width 4 :color ,base00-1 :style nil)
                              :background ,base00-1 :foreground ,base03 :height 0.95))))
   `(mode-line-inactive ((,class (:box (:line-width 4 :color ,base00-1 :style nil)
                                       :background ,base00-1 :foreground ,base01 :height 0.95))))
   `(mode-line-buffer-id ((,class (:foreground unspecified :background nil))))
   `(font-lock-comment-face ((,class (:foreground ,base01))))
   `(font-lock-comment-delimiter-face ((,class (:foreground ,base01))))
   `(font-lock-doc-face ((,class (:foreground ,base02))))
   `(font-lock-string-face ((,class (:foreground ,green))))
   `(font-lock-keyword-face ((,class (:foreground ,purple))))
   `(font-lock-builtin-face ((,class (:foreground ,cyan))))
   `(font-lock-function-name-face ((,class (:foreground ,blue))))
   `(font-lock-variable-name-face ((,class (:foreground ,orange))))
   `(font-lock-type-face ((,class (:foreground ,pink))))
   `(font-lock-constant-face ((,class (:foreground ,cyan))))
   `(font-lock-preprocessor-face ((,class (:foreground ,blue-1))))
   `(font-lock-negation-char-face ((,class (:foreground ,red-1))))
   `(font-lock-warning-face ((,class (:foreground ,red))))
   `(show-paren-match ((,class (:background unspecified :underline (:style line :color ,orange)))))
   `(show-paren-mismatch ((,class (:background unspecified :foreground ,red :inverse-video t))))
   `(match ((,class (:foreground ,yellow-1 :background ,base00+1 :weight bold))))
   `(isearch ((,class (:inherit match))))
   `(query-replace ((,class (:inherit isearch))))
   `(lazy-highlight ((,class (:foreground ,yellow-1))))
   `(isearch-fail ((,class (:foreground ,red :weight bold))))
   `(centaur-tabs-default ((t (:foreground ,base02 :background ,base00-2 :box nil))))
   `(centaur-tabs-selected ((t (:foreground ,base03 :background ,base00 :box nil))))
   `(centaur-tabs-unselected ((t (:foreground ,base01 :background ,base00-1 :box nil))))
   `(centaur-tabs-selected-modified ((t (:foreground ,orange :background ,base00 :box nil))))
   `(centaur-tabs-unselected-modified ((t (:foreground ,orange :background ,base00-1 :box nil))))
   `(company-tooltip ((,class (:background ,base00-1 :foreground ,base02))))
   `(company-tooltip-selection ((,class (:background ,base00-2 :foreground ,base03))))
   `(company-tooltip-common ((,class (:inherit company-tooltip))))
   `(company-scrollbar-bg ((,class (:background ,base00+1))))
   `(company-scrollbar-fg ((,class (:background ,base00+3))))
   `(company-preview ((,class (:background ,base00 :foreground ,base02))))
   `(company-preview-common ((,class (:foreground ,base02))))
   `(tooltip ((,class (:background ,base03 :foreground ,base00 :height 0.9))))
   `(flycheck-error ((,class (:underline (:style wave :color ,red) :inherit unspecified))))
   `(flycheck-info ((,class (:underline (:style wave :color ,green) :inherit unspecified))))
   `(flycheck-warning ((,class (:underline (:style wave :color ,orange) :inherit unspecified))))
   `(dired-directory ((,class (:foreground ,brown))))
   `(markdown-url-face ((,class (:inherit link))))
   `(markdown-link-face ((,class (:foreground ,blue :underline t))))
   `(markdown-header-face-1 ((,class (:foreground ,orange :weight bold))))
   `(markdown-header-face-2 ((,class (:foreground ,purple :weight bold))))
   `(markdown-header-face-3 ((,class (:foreground ,cyan :weight bold))))
   `(markdown-header-face-4 ((,class (:foreground ,teal :weight bold))))
   `(markdown-code-face ((,class (:background ,base00-1 :extend t))))
   `(markdown-pre-face ((,class (:background ,base00-1 :extend t))))
   `(org-done ((,class (:foreground ,green))))
   `(org-todo ((,class (:foreground ,red))))
   `(org-link ((,class (:inherit link))))
   `(org-code ((,class (:foreground ,orange))))
   `(org-block ((,class (:foreground ,base03 :background ,base00+1))))
   `(org-block-background ((,class (:background ,base00+1))))
   `(org-meta-line ((,class (:inherit font-lock-comment-face))))
   `(org-block-end-line ((,class (:inherit font-lock-comment-face))))
   `(org-document-title ((,class (:weight bold :foreground ,orange :height 1.44))))
   `(org-level-1 ((,class (:foreground ,orange :height 1.3 :weight bold))))
   `(org-level-2 ((,class (:foreground ,purple :height 1.2 :weight bold))))
   `(org-level-3 ((,class (:foreground ,cyan :height 1.1 :weight bold))))
   `(org-level-4 ((,class (:foreground ,teal :weight bold))))
   `(org-level-5 ((,class (:foreground ,green))))
   `(org-level-6 ((,class (:foreground ,blue))))
   `(org-level-7 ((,class (:foreground ,pink))))
   `(org-level-8 ((,class (:foreground ,indigo))))
   `(magit-hash ((,class (:foreground ,cyan))))
   `(magit-branch-local ((,class (:foreground ,green-1))))
   `(magit-branch-remote ((,class (:foreground ,green-1))))
   `(magit-section-heading ((,class (:foreground ,orange))))
   `(magit-section-highlight ((,class (:inherit highlight))))
   `(magit-diff-added ((,class (:foreground ,green :background unspecified))))
   `(magit-diff-removed ((,class (:foreground ,red :background unspecified))))
   `(magit-diff-added-highlight ((,class (:foreground ,green :background ,base00-1))))
   `(magit-diff-removed-highlight ((,class (:foreground ,red :background ,base00-1))))
   `(magit-diff-context-highlight ((,class (:foreground unspecified :background ,base00-1))))
   `(diff-added ((,class (:foreground ,green))))
   `(diff-removed ((,class (:foreground ,red))))
   `(diff-changed ((,class (:foreground ,blue))))
   `(diff-header ((,class (:background ,base00+1))))
   `(rainbow-delimiters-depth-1-face ((,class (:foreground ,purple))))
   `(rainbow-delimiters-depth-2-face ((,class (:foreground ,orange))))
   `(rainbow-delimiters-depth-3-face ((,class (:foreground ,cyan))))
   `(rainbow-delimiters-depth-4-face ((,class (:foreground ,green))))
   `(rainbow-delimiters-depth-5-face ((,class (:foreground ,blue))))
   `(rainbow-delimiters-depth-6-face ((,class (:foreground ,pink))))
   `(rainbow-delimiters-depth-7-face ((,class (:foreground ,teal))))
   `(rainbow-delimiters-depth-8-face ((,class (:foreground ,yellow-1))))
   `(rainbow-delimiters-depth-9-face ((,class (:foreground ,indigo))))
   `(rainbow-delimiters-mismatched-face ((,class (:foreground ,red))))
   `(rainbow-delimiters-unmatched-face ((,class (:foreground ,red))))
   `(undo-tree-visualizer-current-face ((,class (:foreground ,green :weight bold))))
   `(compilation-info ((,class (:foreground ,base02 :underline t))))
   `(compilation-line-number ((,class (:foreground ,base02))))
   `(eshell-prompt ((,class (:foreground ,orange :weight bold))))
   `(eshell-ls-directory ((,class (:foreground ,brown))))
   `(wgrep-face ((,class (:background ,base00+2))))
   `(wgrep-file-face ((,class (:background ,base00+1))))
   `(wgrep-delete-face ((,class (:foreground ,red))))
   `(wgrep-done-face ((,class (:foreground ,green))))))
(custom-theme-set-variables
 'apropospriate-claude-dark
 `(ansi-color-names-vector
   ["#2c2c2a" "#e04040" "#9be963" "#fbad60" "#3d8fe0" "#cc7bf4" "#5eedee" "#d3d7de"]))
(provide-theme 'apropospriate-claude-dark)
;;; apropospriate-claude-dark-theme.el ends here
